// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.1
// LVGL version: 9.1.0
// Project name: SquareLine_Project

#include "../ui.h"

lv_obj_t * ui_Screen1 = NULL;
lv_obj_t * ui_batteryBar = NULL;
lv_obj_t * ui_batteryPercent = NULL;
lv_obj_t * ui_timeHour = NULL;
lv_obj_t * ui_timeMinute = NULL;
lv_obj_t * ui_textStep = NULL;
lv_obj_t * ui_textHeart = NULL;
lv_obj_t * ui_Image9 = NULL;
lv_obj_t * ui_ImageHeart = NULL;
lv_obj_t * ui_ImageStep = NULL;
lv_obj_t * ui_logoVision = NULL;
// event funtions

// build funtions

void ui_Screen1_screen_init(void)
{
    ui_Screen1 = lv_obj_create(NULL);
    lv_obj_remove_flag(ui_Screen1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Screen1, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Screen1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_batteryBar = lv_bar_create(ui_Screen1);
    lv_bar_set_value(ui_batteryBar, 80, LV_ANIM_OFF);
    lv_bar_set_start_value(ui_batteryBar, 0, LV_ANIM_OFF);
    lv_obj_set_width(ui_batteryBar, 45);
    lv_obj_set_height(ui_batteryBar, 20);
    lv_obj_set_x(ui_batteryBar, 87);
    lv_obj_set_y(ui_batteryBar, -119);
    lv_obj_set_align(ui_batteryBar, LV_ALIGN_CENTER);

    lv_obj_set_style_bg_color(ui_batteryBar, lv_color_hex(0x00FF00), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_batteryBar, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    //Compensating for LVGL9.1 draw crash with bar/slider max value when top-padding is nonzero and right-padding is 0
    if(lv_obj_get_style_pad_top(ui_batteryBar, LV_PART_MAIN) > 0) lv_obj_set_style_pad_right(ui_batteryBar,
                                                                                                 lv_obj_get_style_pad_right(ui_batteryBar, LV_PART_MAIN) + 1, LV_PART_MAIN);
    ui_batteryPercent = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_batteryPercent, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_batteryPercent, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_batteryPercent, 86);
    lv_obj_set_y(ui_batteryPercent, -119);
    lv_obj_set_align(ui_batteryPercent, LV_ALIGN_CENTER);
    lv_label_set_text(ui_batteryPercent, "80");
    lv_obj_set_style_text_font(ui_batteryPercent, &lv_font_montserrat_14, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_timeHour = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_timeHour, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_timeHour, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_timeHour, 0);
    lv_obj_set_y(ui_timeHour, -41);
    lv_obj_set_align(ui_timeHour, LV_ALIGN_CENTER);
    lv_label_set_text(ui_timeHour, "07");
    lv_obj_set_style_text_font(ui_timeHour, &ui_font_blinkerSemiBold120, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_timeMinute = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_timeMinute, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_timeMinute, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_timeMinute, 0);
    lv_obj_set_y(ui_timeMinute, 49);
    lv_obj_set_align(ui_timeMinute, LV_ALIGN_CENTER);
    lv_label_set_text(ui_timeMinute, "16");
    lv_obj_set_style_text_font(ui_timeMinute, &ui_font_blinkerSemiBold120, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_textStep = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_textStep, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_textStep, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_textStep, -35);
    lv_obj_set_y(ui_textStep, 110);
    lv_obj_set_align(ui_textStep, LV_ALIGN_CENTER);
    lv_label_set_text(ui_textStep, "text");
    lv_obj_set_style_text_font(ui_textStep, &lv_font_montserrat_14, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_textHeart = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_textHeart, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_textHeart, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_textHeart, 79);
    lv_obj_set_y(ui_textHeart, 110);
    lv_obj_set_align(ui_textHeart, LV_ALIGN_CENTER);
    lv_label_set_text(ui_textHeart, "text");
    lv_obj_set_style_text_font(ui_textHeart, &lv_font_montserrat_14, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Image9 = lv_image_create(ui_Screen1);
    lv_obj_set_width(ui_Image9, LV_SIZE_CONTENT);   /// 512
    lv_obj_set_height(ui_Image9, LV_SIZE_CONTENT);    /// 512
    lv_obj_set_x(ui_Image9, 267);
    lv_obj_set_y(ui_Image9, 347);
    lv_obj_set_align(ui_Image9, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image9, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_remove_flag(ui_Image9, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_transform_scale(ui_Image9, 20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ImageHeart = lv_image_create(ui_Screen1);
    lv_image_set_src(ui_ImageHeart, &ui_img_36572657);
    lv_obj_set_width(ui_ImageHeart, LV_SIZE_CONTENT);   /// 64
    lv_obj_set_height(ui_ImageHeart, LV_SIZE_CONTENT);    /// 64
    lv_obj_set_x(ui_ImageHeart, 39);
    lv_obj_set_y(ui_ImageHeart, 110);
    lv_obj_set_align(ui_ImageHeart, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_ImageHeart, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_remove_flag(ui_ImageHeart, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_image_set_scale(ui_ImageHeart, 128);

    ui_ImageStep = lv_image_create(ui_Screen1);
    lv_image_set_src(ui_ImageStep, &ui_img_1522369744);
    lv_obj_set_width(ui_ImageStep, LV_SIZE_CONTENT);   /// 64
    lv_obj_set_height(ui_ImageStep, LV_SIZE_CONTENT);    /// 64
    lv_obj_set_x(ui_ImageStep, -82);
    lv_obj_set_y(ui_ImageStep, 108);
    lv_obj_set_align(ui_ImageStep, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_ImageStep, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_remove_flag(ui_ImageStep, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_image_set_scale(ui_ImageStep, 192);

    ui_logoVision = lv_image_create(ui_Screen1);
    lv_image_set_src(ui_logoVision, &ui_img_hanwha_vision_rgb_eeh_png);
    lv_obj_set_width(ui_logoVision, LV_SIZE_CONTENT);   /// 127
    lv_obj_set_height(ui_logoVision, LV_SIZE_CONTENT);    /// 52
    lv_obj_set_x(ui_logoVision, -54);
    lv_obj_set_y(ui_logoVision, -118);
    lv_obj_set_align(ui_logoVision, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_logoVision, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_remove_flag(ui_logoVision, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

}

void ui_Screen1_screen_destroy(void)
{
    if(ui_Screen1) lv_obj_del(ui_Screen1);

    // NULL screen variables
    ui_Screen1 = NULL;
    ui_batteryBar = NULL;
    ui_batteryPercent = NULL;
    ui_timeHour = NULL;
    ui_timeMinute = NULL;
    ui_textStep = NULL;
    ui_textHeart = NULL;
    ui_Image9 = NULL;
    ui_ImageHeart = NULL;
    ui_ImageStep = NULL;
    ui_logoVision = NULL;

}
