// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.1
// LVGL version: 9.1.0
// Project name: SquareLine_Project

#ifndef UI_SCREEN1_H
#define UI_SCREEN1_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_Screen1
extern void ui_Screen1_screen_init(void);
extern void ui_Screen1_screen_destroy(void);
extern lv_obj_t * ui_Screen1;
extern lv_obj_t * ui_batteryBar;
extern lv_obj_t * ui_batteryPercent;
extern lv_obj_t * ui_timeHour;
extern lv_obj_t * ui_timeMinute;
extern lv_obj_t * ui_textStep;
extern lv_obj_t * ui_textHeart;
extern lv_obj_t * ui_Image9;
extern lv_obj_t * ui_ImageHeart;
extern lv_obj_t * ui_ImageStep;
extern lv_obj_t * ui_logoVision;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

