// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.1
// LVGL version: 9.1.0
// Project name: SquareLine_Project

#ifndef _UI_COMP_IMAGE10_H
#define _UI_COMP_IMAGE10_H

#include "../ui.h"

#ifdef __cplusplus
extern "C" {
#endif

// COMPONENT Image10
#define UI_COMP_IMAGE10_IMAGE10 0
#define _UI_COMP_IMAGE10_NUM 1
lv_obj_t * ui_Image10_create(lv_obj_t * comp_parent);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
