// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.1
// LVGL version: 9.1.0
// Project name: SquareLine_Project

#include "../ui.h"

// COMPONENT batteryText2

lv_obj_t * ui_batteryText2_create(lv_obj_t * comp_parent)
{

    lv_obj_t * cui_batteryText2;
    cui_batteryText2 = lv_label_create(comp_parent);
    lv_obj_set_width(cui_batteryText2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(cui_batteryText2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(cui_batteryText2, 87);
    lv_obj_set_y(cui_batteryText2, -117);
    lv_obj_set_align(cui_batteryText2, LV_ALIGN_CENTER);
    lv_label_set_text(cui_batteryText2, "80%");
    lv_obj_set_style_text_font(cui_batteryText2, &lv_font_montserrat_14, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_t ** children = lv_malloc(sizeof(lv_obj_t *) * _UI_COMP_BATTERYTEXT2_NUM);
    children[UI_COMP_BATTERYTEXT2_BATTERYTEXT2] = cui_batteryText2;
    lv_obj_add_event_cb(cui_batteryText2, get_component_child_event_cb, LV_EVENT_GET_COMP_CHILD, children);
    lv_obj_add_event_cb(cui_batteryText2, del_component_child_event_cb, LV_EVENT_DELETE, children);
    ui_comp_batteryText2_create_hook(cui_batteryText2);
    return cui_batteryText2;
}

