// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.1
// LVGL version: 9.1.0
// Project name: SquareLine_Project

#include "../ui.h"

// COMPONENT Image10

lv_obj_t * ui_Image10_create(lv_obj_t * comp_parent)
{

    lv_obj_t * cui_Image10;
    cui_Image10 = lv_image_create(comp_parent);
    lv_image_set_src(cui_Image10, &ui_img_1522369744);
    lv_obj_set_width(cui_Image10, LV_SIZE_CONTENT);   /// 213
    lv_obj_set_height(cui_Image10, LV_SIZE_CONTENT);    /// 512
    lv_obj_set_x(cui_Image10, 14);
    lv_obj_set_y(cui_Image10, 101);
    lv_obj_set_align(cui_Image10, LV_ALIGN_CENTER);
    lv_obj_add_flag(cui_Image10, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_remove_flag(cui_Image10, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    lv_obj_t ** children = lv_malloc(sizeof(lv_obj_t *) * _UI_COMP_IMAGE10_NUM);
    children[UI_COMP_IMAGE10_IMAGE10] = cui_Image10;
    lv_obj_add_event_cb(cui_Image10, get_component_child_event_cb, LV_EVENT_GET_COMP_CHILD, children);
    lv_obj_add_event_cb(cui_Image10, del_component_child_event_cb, LV_EVENT_DELETE, children);
    ui_comp_Image10_create_hook(cui_Image10);
    return cui_Image10;
}

