// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.1
// LVGL version: 9.1.0
// Project name: SquareLine_Project

#include "../ui.h"

void ui_comp_Image10_create_hook(lv_obj_t * comp)
{
}

void ui_comp_batteryText2_create_hook(lv_obj_t * comp)
{
}
