// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.1
// LVGL version: 9.1.0
// Project name: SquareLine_Project

#ifndef _UI_COMP_BATTERYTEXT2_H
#define _UI_COMP_BATTERYTEXT2_H

#include "../ui.h"

#ifdef __cplusplus
extern "C" {
#endif

// COMPONENT batteryText2
#define UI_COMP_BATTERYTEXT2_BATTERYTEXT2 0
#define _UI_COMP_BATTERYTEXT2_NUM 1
lv_obj_t * ui_batteryText2_create(lv_obj_t * comp_parent);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
